import Head from "next/head";

export default function AccountPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 data-testid="welcome-header text-xl">
           <a href="#">Account</a>
        </h1>
      </main>
    </div>
  );
}
