import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [merchants, setMerchants] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    axios
      .get("/api/merchants")
      .then((res) => {
        setMerchants(res.data);
      })
      .catch((error) => {
        setError(error);
        console.trace(error);
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 data-testid="welcome-header">
          Welcome to <a href="#">Kantin Fasilkom</a>
        </h1>

        <h2>List Merchant</h2>

        {loading && <h2>Loading...</h2>}

        {error && <h2>Terjadi Kesalahan</h2>}

        {merchants.map((merchant) => (
          <div key={merchant.id}>
            <h3>{merchant.name}</h3>
            <ul>
              {merchant.products.map((product) => (
                <li key={product.id}>{product.name}</li>
              ))}
            </ul>
          </div>
        ))}
      </main>
    </div>
  );
}
