import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 data-testid="welcome-header text-xl">
          <a href="#">Welcome to Gocanteen</a>
        </h1>

        <div className="mt-8">
          <h2>How to use</h2>
          <p className="mt-4">
            <ol className="list-decimal list-inside">
              <li>
                Visit your canteen or cafeteria who already partnered with
                GoCanteen
              </li>
              <li>
                Scan the QR Code on the table or on the menu to order your food
              </li>
              <li>
                Pay, then wait for your food to be served and enjoy your meal
              </li>
            </ol>
          </p>
        </div>
      </main>
    </div>
  );
}
